Algoritmo "Lt01_EstRep39"
Var
   Casa, Qtde, Total : Real
Inicio
   Casa <- 1
   Qtde <- 1
   Enquanto Casa <= 32 faca
      Escreva (Casa)
      Escreval (Qtde)
      Casa <- Casa + 1
      Qtde <- Qtde * 2
      Total <- Total + Qtde
   FimEnquanto
   Escreval ("O total é: ", Total)
Fimalgoritmo

//39-Calcule a quantidade de grãos contidos em um tabuleiro de xadrez onde:
//Casa : 1  2  3  4  ...  64
//Qdte : 1  2  4  8  ...   N .

Algoritmo "LT01_FUN39"
Var

Inicio

FimAlgoritmo