Algoritmo "LT01_ModEx19"
Var
   X, Y : Inteiro
Procedimento Maior()
Inicio
   Se X > Y entao
      Escreval (X," é o número maior")
   Senao
      Se Y > X entao
         Escreval (Y," é o número maior")
      Senao
         Escreval ("Números Iguais ")
      Fimse
   Fimse
FimProcedimento
Inicio
   Escreval ("Digite um valor: ")
   Leia (X)
   Escreval ("Digite outro valor: ")
   Leia (Y)
   Maior ()
Fimalgoritmo